require 'settings'
require 'maps'
require 'plugins'
require 'colorscheme'
require 'nvim-tree-config'
require 'telescope-config'
require 'treesitter-config'
require 'whichkey-config'
require 'lualine-config'
require 'trouble-config'
require 'cmp-config'
require 'lsp-config'
require 'autopairs-config'
require 'null-ls-config'
require 'lspsaga-config'
require 'bufferline-config'

